[17기 심규보] SingInView 작성
wecode-bootcamp-korea/17-1st-StyleWe-backend pull request #3
Opened 2021-02-20 05:21 UTC by Gyubster

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 Logic 구현
		 
## 수정 사항들 자세한 내용
- bcrypt로 password 암호화
- jwt로 token 발행

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-22 01:52 UTC, soheon-lee commented on user/views.py
> +
Token 암호화 알고리즘이 노출되었습니다. 보안에 굉장히 취약해지니 secret_key와 마찬가지로 별도의 모듈로 분리시켜 관리해주세요 :)

2021-02-22 01:52 UTC, soheon-lee commented on user/views.py
> +
없는 `user_name`으로 해당 엔드포인트 호출을 시도했을 때 어떤 에러가 나오는지 한 번 캡쳐해서 보여주세요~

2021-02-22 01:53 UTC, soheon-lee commented on user/urls.py
> +    path('signin/', SignInView.as_view()),
RESTful API 규칙에서는 API url의 마지막에 슬래시('/')를 붙이지 않습니다 :)

2021-02-22 01:54 UTC, soheon-lee commented on config/urls.py
> +        path('user/', include('user.urls'))
```suggestion
        path('user', include('user.urls'))
```
main url에서는 슬래시를 붙이지 않는 것이 wecode conding convention입니다 👍 
슬래시는 app url에서 공통적으로 다뤄주시는 것이 좋습니다 :)

2021-02-22 05:04 UTC, Gyubster commented on user/views.py
> +
DoesNotExist 에러가 나겠군요..! 에러처리해서 곧올리도록하겠습니다!

2021-02-22 08:35 UTC, soheon-lee commented on user/views.py
> +from my_settings            import SECRET_KEY, AL
```suggestion
from my_settings            import SECRET_KEY, ALGORITHM
```
`AL`은 다소 명확하지 않은 변수 이름입니다.
꼭 필요한 경우가 아니라면 줄임말은 되도록 쓰지 않는 것을 추천드립니다 :)

2021-02-22 08:35 UTC, soheon-lee commented on user/views.py
> +
exception으로 잡아주셨군요👍
보통 파이썬에서는 exception 처리는 코드의 가장 아래에서 해주시는 것이 일반적입니다.

추가적으로, exception으로 에러 핸들링 하는 방법을 사용할 때에 주의 사항이 있습니다.  DoesNotExist 가 발생할 수 있는 로직에서는, 이렇게 바로 에러 처리를 하는 것 보다는 if 조건문으로 먼저 데이터 존재 여부를 따져보는 것이 좋습니다. (ex. if `exists()`)

로직상에서 잡을 수 있는 에러는 모두 잡고, 정말 어쩔 수 없는 경우에 exception 처리를 해주는 것이 좋습니다.

2021-02-23 01:34 UTC, soheon-lee commented on user/views.py
> +
엇? 이부분 삭제하셨네요 ㅎㅎ
이따 오후에 잠깐 봬요 규보님!

2021-02-23 02:16 UTC, lordmyshepherd requested changes

2021-02-23 02:16 UTC, lordmyshepherd commented on user/views.py
> +            user = User.objects.get(user_name=user_name)
`user_name`으로 로그인 하시는 것 같은데, `unique`한 값인가요?

2021-02-23 02:16 UTC, lordmyshepherd commented on user/views.py
> +            if password_validation:
비밀번호를 확인한 후에 변수에 할당해주는 이유가 있으신가요?
그렇지 않다면, 3줄을 1줄로 줄이는게 좋을 것 같습니다.

```python
if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
```

2021-02-23 02:16 UTC, lordmyshepherd commented on user/views.py
> +                return JsonResponse({'message':'SUCESS', "token":acces_token}, status=200)
서버에서 발급해주는 token이 어떤 token인지 명확하게 만들어주세요.
나중에는 refresh_token 등 다양한 토큰을 서버에서 관리해야되는데, `token`은 어떤 토큰인지 의미가 분명하지 않습니다.
```suggestion
                return JsonResponse({'message':'SUCESS', "access_token":acces_token}, status=200)
```

2021-02-23 02:43 UTC, lordmyshepherd commented
> 규보님 모든 리뷰 코멘트에 확인하셨고, 수정 반영했다는 코멘트를 남겨주세요!

2021-02-23 03:14 UTC, Gyubster commented on user/views.py
> +
네 알겠습니다! 이부분 If방식으로 처리했습니다

2021-02-23 04:13 UTC, Gyubster commented on user/views.py
> +            user = User.objects.get(user_name=user_name)
unique=True를 db에서는 하지않았습니다.

views.py에서 중복값이 들어가지않게 로직을 구현해서 문제가 없을거라고 생각했습니다.

 models.py에 user_name을  unique=True로 설정해야될까요..?

2021-02-23 04:13 UTC, Gyubster commented on user/views.py
> +            if password_validation:
네 알겠습니다!

2021-02-23 04:16 UTC, Gyubster commented on user/views.py
> +                return JsonResponse({'message':'SUCESS', "token":acces_token}, status=200)
수정했습니다!

2021-02-23 05:04 UTC, Gyubster commented
unique=True 질문사항 제외 수정사항 반영했습니다.

2021-02-23 05:22 UTC, soheon-lee commented
LGTM

2021-02-23 05:22 UTC, merged