[17기 심규보] SignUpFinalizeView 생성
wecode-bootcamp-korea/17-1st-StyleWe-backend pull request #6
Opened 2021-02-22 05:23 UTC by Gyubster

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 최종페이지 로직 구현
		 
## 수정 사항들 자세한 내용
- 데코레이터를 통해 유저 인증을 받은 사람들만 유저정보관련 추가사항을 수정할 수 있게 함

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-22 08:37 UTC, soheon-lee commented on user/utils.py
> +from my_settings        import SECRET_KEY, AL
`AL` 줄임말로 지정하신 변수 풀어써주세요 :)

2021-02-22 08:37 UTC, soheon-lee commented on user/utils.py
> +
DoesNotExist에러 정상적으로 잘 잡히는 것 맞나요?

2021-02-22 08:37 UTC, soheon-lee commented on user/views.py
> +            return JsonResponse({'message':'INVALID_KEYS'}, status=400)
데코레이터 정상 작동 안할 것 같은데, 테스트 해보셨나요?

2021-02-22 09:12 UTC, Gyubster commented on user/utils.py
> +
어 이거 대문자 User.DoesNotExist로 작성했을때 해결됬습니다. 이전에 수정햇는데 반영이 안됬나보네요. 다시 올리겠습니다.

2021-02-22 11:03 UTC, Gyubster commented on user/views.py
> +            return JsonResponse({'message':'INVALID_KEYS'}, status=400)
제가 중간중간 테스트해본데서 옮겨오다가 오타가 나왔네요! 다 수정해서 올렸습니다

2021-02-22 11:03 UTC, Gyubster commented on user/utils.py
> +from my_settings        import SECRET_KEY, AL
확인했습니다.

2021-02-23 01:22 UTC, soheon-lee commented
@Gyubster 규보님 커밋 메세지는 단순히 어떤 파일 수정했는지를 기록하는 장치가 아닙니다 :) 어떤 파일 수정했는지는 커밋에 git이 자동으로 기록합니다. 내가 어떤 작업을 수행했는지, 어떤 과정을 수정했는지를 기록하셔야 합니다. 해당 커밋에 어떤 작업을 했는지 알 수 없는 메세지가 모두 똑같이 있다면, 이는 커밋으로서의 제 역할을 하지 못한다고 볼 수 있습니다 :) 다음 커밋부터는 작업 내용 정확히 적어주세요~

2021-02-23 02:41 UTC, lordmyshepherd requested changes

2021-02-23 02:41 UTC, lordmyshepherd commented on user/views.py
> +class SignUpFinalizeView(View):
규보님 `SignupFinalizeView`는 회원가입 페이지를 기준으로 엔드포인트를 작성하신 것 같아요!
`Backend API`는 페이지를 기준으로 작성하시는 것을 피해주시고, 데이터 기준으로 만들려고 노력해주시면 좋을 것 같아요!

데이터 기준으로 생각해보면, 해당 View는 이전 작업에서 생성된 `User` 데이터를 업데이트 하는 작업을 수행한다고 볼 수 있을 것 같네요.

> SignupFinalize가 아니라 사용자 정보를 업데이트할 수 있는 엔드포인트로, class명과 연결되는 URI를 수정해주세요!

2021-02-23 02:41 UTC, lordmyshepherd commented on user/utils.py
> +def login_decorator(func):
데코레이터는 이전 pr에 있던 것 같은데 여기도 있네요??

2021-02-23 02:44 UTC, lordmyshepherd commented
> 규보님 모든 리뷰 코멘트에 확인하셨고, 수정 반영했다는 코멘트를 남겨주세요!

2021-02-23 04:24 UTC, Gyubster commented on user/views.py
> +class SignUpFinalizeView(View):
네 알겠습니다. 이름변경 이후에는 Branch 및 pr 제목도 그에 맞게 변경하면 될까요?

2021-02-23 04:27 UTC, Gyubster commented on user/utils.py
> +def login_decorator(func):
데코레이터가 사실 이부분에서 사용되는데 제가 브랜치이동하면서 켜놓은 utils.py의 수정사항을 저장시켰나보네요..ㅜ 

제 생각에는 SignUpFinalize branch 부분에서만 존재해야되는 파일 같은데 SignUpInitializeView branch의 utils.py를 지울까요?

2021-02-23 05:24 UTC, soheon-lee commented on user/views.py
> +class SignUpFinalizeView(View):
클래스 이름만 바꿔주세요 :)

2021-02-23 10:11 UTC, lordmyshepherd commented on user/utils.py
> +def login_decorator(func):
네 규보님! 수정해주세요~

2021-02-25 01:59 UTC, soheon-lee commented
==============CLOSED======================

2021-02-25 01:59 UTC, closed without merging