[17기 심규보] SignUpInitializeView 생성
wecode-bootcamp-korea/17-1st-StyleWe-backend pull request #7
Opened 2021-02-22 05:54 UTC by Gyubster

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- SignUpInitializeView 생성
		 
## 수정 사항들 자세한 내용
- 최소 비밀번호 길이 제한
- 최소 및 최대 아이디 길이 제한
- user 비밀번호 암호화
- user.id를 이용하여 토큰 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-02-22 08:41 UTC, soheon-lee commented on user/views.py
> +
```suggestion

            if User.objects.filter(user_name=user_name).exists():
                return JsonResponse({'message':'USER_NAME_ALREADY_EXISTS'}, status=409)
            if User.objects.filter(email=email).exists():
                return JsonResponse({'message':'EMAIL_ALREADY_EXISTS'}, status=409)

            if len(user_name) < USER_NAME_MIN_LENGTH:
                return JsonResponse({'message':'SHORT_ID'}, status=400)
            if len(user_name) > USER_NAME_MAX_LENGTH:
                return JsonResponse({'message':'LONG_ID'}, status=409)
            if len(password) < PASSWORD_MIN_LENGTH:
                return JsonResponse({'message':'SHORT_PASSWORD'}, status=409)
            
```
validation 꼼꼼하게 잘 하셨네요 👍 
연산자는 앞뒤로 공백을 주시는 것이 좋습니다.
그리고 user_name 길이는 두 조건을 if 문에서 동시에 판별하지 않고 따로 보내시는 것은, validation 때문인가요?

2021-02-22 08:41 UTC, soheon-lee commented on user/views.py
> +
```suggestion
            User.objects.create(
                user_name   = user_name,
                password    = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode(),
                nickname    = nickname,
                email       = email
            )

```
괄호의 위치를 조정하여, 코드끼리의 포함관계를 시각적으로 명화가게 해주시는 것이 좋습니다 👍

2021-02-22 08:59 UTC, Gyubster commented on user/views.py
> +
넵! message로 길고 짧은 정도를 알려주는게 좋을것같아서 그렇게 표현했습니다.

2021-02-23 01:23 UTC, soheon-lee commented
여기도 커밋메세지 마찬가지입니다 :)

2021-02-23 02:37 UTC, lordmyshepherd requested changes

2021-02-23 02:37 UTC, lordmyshepherd commented on user/utils.py
> +    def wrapper(self, request, *args, **kwargs):
`*args, **kwargs`를 인자로 받는 이유는 무엇인가요?
```suggestion
    def wrapper(self, request, *args, **kwargs):
```

2021-02-23 02:37 UTC, lordmyshepherd commented on user/views.py
> +            user    = User.objects.get(user_name=user_name)
line 38에서 ojbects manager class의 `create()` method를 호출한 이후에 다시 `get()`을 호출하신 이유가 있나요?

2021-02-23 05:13 UTC, Gyubster commented on user/views.py
> +            user    = User.objects.get(user_name=user_name)
생성한 user에 대해서 다시 접근해야되는 줄 알았습니다. user = User.objects.create()으로 지정하는 방법이 가능한 것을 방금 확인하여서 이로 수정하겠습니다.

2021-02-23 05:14 UTC, Gyubster commented on user/utils.py
> +    def wrapper(self, request, *args, **kwargs):
이부분 개념이 부족한것같습니다. 조금 더 찾아보고 정리해서 답글 남기도록하겠습니다.

2021-02-23 05:17 UTC, Gyubster commented
수정사항 반영했습니다.

2021-02-23 12:39 UTC, soheon-lee commented on user/urls.py
> +        path('/signup/final', UserView.as_view()),
```suggestion
        path('/signup', UserView.as_view()),
```
서로 메소드가 다르기 때문에 이미 분리되어 있으므로, url 두개로 사용하지 않으셔도 됩니다

2021-02-23 16:21 UTC, Gyubster commented
CONFLICT를 일으킨 파일들을 수정하고 이유모를 문제로 push가 안되서..

 git push +feature/signupinitialize 로 push를 마쳤습니다. 

이 방법으로 해도 괜찮은건가요?

2021-02-24 01:28 UTC, soheon-lee commented
> CONFLICT를 일으킨 파일들을 수정하고 이유모를 문제로 push가 안되서..
> 
> git push +feature/signupinitialize 로 push를 마쳤습니다.
> 
> 이 방법으로 해도 괜찮은건가요?

네, 원래도 push 할 때는 
`git push origin featrue/signupinitialize` 명령어를 사용하시지 않으셨나요?

2021-02-24 01:32 UTC, soheon-lee commented on user/views.py
> +            user    = User.objects.get(id=request.user.id)
데코레이터 활용해서 user 객체 받으셨군요! good good!

```suggestion
            user    = request.user
```
request에 들어있는 `user`이라는 속성이 이미, django User 객체입니다 :)
왜냐하면 `login decorator`에서
```python
            user            = User.objects.get(id=payload['user_id'])
            request.user    = user
```
이렇게 request.user에 할당해준 객체가 User객체이기 때문입니다 :) 이해가 혹시 되셨을까요?
따라서 views파일에서는 request에 들어있는 user 인스턴스를 바로 사용하실 수 있습니다

2021-02-24 01:32 UTC, soheon-lee commented on user/utils.py
> +    def wrapper(self, request, *args, **kwargs):
여기 병민님이 말씀해주신 `*args`랑 `**kwargs` 왜 사용하는지 정리 되셨나요 규보님?

2021-02-24 01:49 UTC, Gyubster commented on user/views.py
> +            user    = User.objects.get(id=request.user.id)
네 이해완료했습니다!

2021-02-24 01:52 UTC, Gyubster commented
1. *args와 *kwargs 는 pack역할을 하는 것으로 이해했습니다. *args에 튜플형태로 모든 arguments들을 넣고, 그리고 이런 *args들을 *kwargs에 넣어서 하나의 딕셔너리로 묶어주는 역할로 이해했습니다.

2. conflict 해결후에 원래의 명령어로 push를 하려고하니 안되고 branch앞에 +를 붙여서 force push를 하니 되었습니다.

2021-02-24 05:45 UTC, soheon-lee commented
@Gyubster 음.. 뭔가 문제가 있어서 push가 안된걸텐데, 해결 하시지 않은 채로 force push를 하셨다면 다른 팀원분들도 push 하실 때도 오류나서 force push 하셔야할 가능성이 있다는 점을 우선 알고 있어주세용! 같이 해결하시면 됩니닷

2021-02-24 05:45 UTC, soheon-lee commented
LGTM

2021-02-24 05:45 UTC, merged

2021-02-24 05:46 UTC, Gyubster commented
네 알겠습니다! 팀원들과 공유하겠습니다.